version: '3.3'
services:
  mysqldb:
    image: mysql:latest
    volumes:
      - /home/mysql/data:/var/lib/mysql
    restart: on-failure
    ports:
      - 3306:3306
    environment:

       MYSQL_DATABASE: achat-db
       MYSQL_ALLOW_EMPTY_PASSWORD: 1


  spring_app:
    depends_on:
      - mysqldb
    image: wissemesprit/achat-docker
    ports:
      - 9090:9090
    restart: on-failure
    container_name: wissem-achat-project

volumes:
  db_data: {}
