version: '3.3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    volumes:
      - /home/mysql/data:/var/lib/mysql:rw
    user: root
    restart: always
    ports:
      - 3308:3306
    environment:

       MYSQL_DATABASE: achat-db
       MYSQL_USER: root
       MYSQL_ALLOW_EMPTY_PASSWORD: 1


  spring_app:
    depends_on:
      - mysqldb
    image: wissemesprit/achat-docker
    ports:
      - 9090:9090
    restart: always
    container_name: wissem-achat-project

