version: "3.4"
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: achatdb
       MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_vol:/var/lib/mysql:rw
  backend:
    image: riadhmars/test-achat
    ports:
      - '8089:8089'
    restart: unless-stopped
    environment :
      -SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/achatdb?createDatabaseIfNotExist=true
    depends_on:
      - mysqldb
  frontapp:
    image: riadhmars/achatfront
    ports:
      - '4200:80'
    depends_on:
      - backend
volumes:
     db_vol: { }