version: "3.4"
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_DATABASE=achatdb
     - MYSQL_PASSWORD=root
    volumes:
      - db_vol:/var/lib/mysql:rw
  backend:
    image: riadhmars/test-achat
    ports:
      - '8089:8089'
    restart: unless-stopped
    environment :
      -SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/achatdb?createDatabaseIfNotExist=true
      -SPRING_DATASOURCE_USERNAME : root
      -SPRING_DATASOURCE_PASSWORD : root
      
    depends_on:
      - mysqldb
  frontapp:
    image: riadhmars/achatfront
    ports:
      - '4200:80'
    depends_on:
      - backend
volumes:
     db_vol: { }