version: '3.3'
services:
  mysqldb:
    image: mysql
    volumes:
      - /home/mysql/data:/var/lib/mysql
    restart: always
    environment:
      
      MYSQL_DATABASE: achat-db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
      
    
  spring_app:
    depends_on:
      - mysqldb
    image: chibeniamine/spring-boot-docker
    ports:
      - 9090:9090
    restart: on-failure
    container_name: amine-achat-project

volumes:
  db_data: {}