version: '3.3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    volumes:
      - mysql_container:/var/lib/mysql:rw
    user: root
    restart: always
    ports:
      - 3308:3306
    environment:

       MYSQL_DATABASE: achat-db
       MYSQL_ALLOW_EMPTY_PASSWORD: 1


  spring_app:
    depends_on:
      - mysqldb
    image: wissemesprit/achat-docker
    ports:
      - 8089:8089
    restart: always
    container_name: spring_app

  front_app:
    depends_on:
      - spring_app
    image: wissemesprit/achat-front
    ports:
      - 4200:80
    restart: always
    container_name: front-container
volumes:
  mysql_container: { }

