version: '3.3'
services:
  mysqldb:
    image: mysql:8
    volumes:
      - /home/mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: achat-db
    ports:
      - 3306:3306
      
    
  spring_app:
    depends_on:
      - mysqldb
    image: chibeniamine/spring-boot-docker
    ports:
      - 9090:9090
    restart: on-failure
    container_name: amine-achat-project

volumes:
  db_data: {}