version: '3.3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    volumes:
      - vlachat:/var/lib/mysql:rw
    user: root
    restart: always
    ports:
      - 3306:3306
    environment:

       MYSQL_DATABASE: achatdb
       MYSQL_ALLOW_EMPTY_PASSWORD: 1


  spring_app:
    depends_on:
      - mysqldb
    image: alaadoc/esprit:ala
    ports:
      - 8089:8089
    environment:
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&enabledTLSProtocols=TLSv1.2
    #restart: always
    container_name: spring_app



# Names our volume
volumes:
  vlachat: