version: '3.3'
services:
  mysqldb:
    image: mysql:8
    volumes:
      - mysql_container:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
      
    
  spring_app:
    depends_on:
      - mysqldb
    image: chibeniamine/spring-boot-docker
    ports:
      - 8089:8089
    restart: always
    container_name: amine-achat-project
    
    volumes:
       mysql_container:{ }
    
       

