version: '3.3'
services:
  mysqldb:
    image: mysql:8
    
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
      
    
  spring_app:
    depends_on:
      - mysqldb
    image: chibeniamine/spring-boot-docker
    ports:
      - 9090:9090
    restart: on-failure
    container_name: amine-achat-project
    environment:
       -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?autoReconnect=true&failOverReadOnly=false&maxReconnects=10
       -SPRING_DATASOURCE_USERNAME : root
    links:
      - mysqldb:mysqldb
       

