version: '3.3'
services:
  mysqldb:
    image: mysql:8
    
    restart: always
    environment:
      
      MYSQL_DATABASE: achatdb
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
      
    
  spring_app:
    depends_on:
      - mysqldb
    image: chibeniamine/spring-boot-docker
    ports:
      - 8089:8089
    restart: always
    container_name: amine-achat-project
    environment:
      -SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10


  angular_app:
    depends_on:
      - spring_app
    image: chibeniamine/front-achat
    ports:
      - 4200:80
    container_name: angular-achat-front
    depends_on:
      -  spring_app
    
    
    
       

